name: Build and Test

on:
  push:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: |
        autoreconf --install
        ./configure
        make check
