name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - branchHTTPservMutli

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build and push images
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dashakond/my-http-server:latest
            dashakond/my-http-server:latest-${{ matrix.platform }}

      # 6. Create and push Docker manifest
      - name: Create and push Docker manifest
        run: |
          docker manifest create dashakond/my-http-server:latest \
            --amend dashakond/my-http-server:latest-amd64 \
            --amend dashakond/my-http-server:latest-arm64
          docker manifest push dashakond/my-http-server:latest
